# Generated by Django 5.1.7 on 2025-04-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("armsApp", "0008_alter_userprofile_photo_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
